export const actionTypes = {
  Post: 'tweet',
  Reply: 'reply',
  Posten: 'tweet',
  Antworten: 'reply',
  Objavi: 'tweet',
  Odgovori: 'reply',
  Posting: 'tweet',
  Balas: 'reply',
  Postovat: 'tweet',
  Odpovědět: 'reply',

  Plaatsen: 'tweet',
  Beantwoorden: 'reply',
  'I-post': 'tweet',
  Sumagot: 'reply',

  Julkaise: 'tweet',
  Vastaa: 'reply',
  Poster: 'tweet',
  Répondre: 'reply',
  Δημοσίευση: 'tweet',
  Απάντηση: 'reply',
  פרסם: 'tweet',
  השב: 'reply',
  पोस्ट: 'tweet',
  'जवाब दें': 'reply',
  Bejegyzés: 'tweet',
  Válasz: 'reply',
  Pubblica: 'tweet',
  Rispondi: 'reply',
  ポストする: 'tweet',
  返信: 'reply',
  게시하기: 'tweet',
  답글: 'reply',
  Publiser: 'tweet',
  Svar: 'reply',
  'Opublikuj wpis ': 'tweet',
  Odpowiedz: 'reply',
  Postar: 'tweet',
  Responder: 'reply',
  Postare: 'tweet',
  Răspunde: 'reply',
  'Опубликовать пост': 'tweet',
  Ответить: 'reply',
  发帖: 'tweet',
  回复: 'reply',
  'Uverejniť ': 'tweet',
  Odpovedať: 'reply',
  Postear: 'tweet',
  'Gör ett inlägg': 'tweet',
  Svara: 'reply',
  發佈: 'tweet',
  回覆: 'reply',
  Gönder: 'tweet',
  Yanıtla: 'reply',
  'Опублікувати пост': 'tweet',
  Відповісти: 'reply',
  Đăng: 'tweet',
  'Trả lời': 'reply',
};
